export const ENV_VARIABLES = {
  TWILIO_LIVE_ACCESS_CREDENTIALS: {
    TWILIO_ACCOUNT_SID: 'TWILIO_ACCOUNT_SID',
    TWILIO_AUTH_TOKEN: 'TWILIO_AUTH_TOKEN',
    TWILIO_SENDGRID_API_KEY: 'TWILIO_SENDGRID_API_KEY',
  },
  TWILIO_TEST_ACCESS_CREDENTIALS: {
    TWILIO_TEST_ACCOUNT_SID: 'TWILIO_TEST_ACCOUNT_SID',
    TWILIO_TEST_AUTH_TOKEN: 'TWILIO_TEST_AUTH_TOKEN',
  },
  TWILIO_LIVE_SMS: {
    TWILIO_PHONE_NUMBER: 'TWILIO_PHONE_NUMBER',
  },
  TWILIO_LIVE_CALL: {
    TWILIO_PHONE_NUMBER: 'TWILIO_PHONE_NUMBER',
  },
  TWILIO_LIVE_WHATSAPP: {
    TWILIO_WHATSAPP_NUMBER: 'TWILIO_WHATSAPP_NUMBER',
  },
  TWILIO_LIVE_EMAIL: {
    TWILIO_SENDER_EMAIL: 'TWILIO_SENDER_EMAIL',
    TWILIO_REPLY_TO_EMAIL: 'TWILIO_REPLY_TO_EMAIL',
  },
};
